export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const REGISTER = "REGISTER";
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const GET_USER_PURCHASE_HISTORY = "GET_USER_PURCHASE_HISTORY";
export const UPDATE_USER_PASSWORD = "UPDATE_USER_PASSWORD";
export const SWITCH_USER_ROLE = "SWITCH_USER_ROLE";

export const CREATE_NEW_COURSE = "CREATE_NEW_COURSE";
export const GET_COURSE_BY_TITLE = "GET_COURSE_BY_TITLE";
export const UPDATE_COURSE_INFO = "UPDATE_COURSE_INFO";
export const GET_COURSE_INFO_BY_ID = "GET_COURSE_INFO_BY_ID";
export const GET_COURSE_CONTENT_BY_ID = "GET_COURSE_CONTENT_BY_ID";
export const GET_ALL_COURSES = "GET_ALL_COURSES";
export const GET_COURSE_BY_CATEGORY = "GET_COURSE_BY_CATEGORY";
export const GET_TEN_MOST_POPULAR_COURSES = "GET_TEN_MOST_POPULAR_COURSES";
export const GET_TEN_MOST_NEWEST_COURSES = "GET_TEN_MOST_NEWEST_COURSES";
export const GET_A_RANDOM_COURSE = "GET_A_RANDOM_COURSE";
export const ADD_COURSE_COMMENT = "ADD_COURSE_COMMENT";
export const GET_COURSE_ALL_COMMENTS = "GET_COURSE_ALL_COMMENTS";
export const ADD_COURSE_TA = "ADD_COURSE_TA";
export const REMOVE_COURSE_TA = "REMOVE_COURSE_TA";
export const GET_COURSE_TAS = "GET_COURSE_TAS";
export const ADD_STUDENT_TO_COURSE = "ADD_STUDENT_TO_COURSE";
export const REMOVE_STUDENT_FROM_COURSE = "REMOVE_STUDENT_FROM_COURSE";
export const GET_COURSE_STUDENTS = "GET_COURSE_STUDENTS";

export const ADD_COURSE_TO_CART = "ADD_COURSE_TO_CART";
export const REMOVE_COURSE_FROM_CART = "REMOVE_COURSE_FROM_CART";
export const GET_CART_ITEMS = "GET_CART_ITEMS";
